import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Kiyoshi",
      email: "admin1@example.com",
      password: bcrypt.hashSync("asdf", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Kiyoshi seller",
        logo: "/images/matsumotokiyoshi.png",
        description: "best seller",
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: "Carrefour",
      email: "admin2@example.com",
      password: bcrypt.hashSync("asdf", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Carrefour seller",
        logo: "/images/seller/carrefour.png",
        description: "best seller",
        rating: 3.5,
        numReviews: 120,
      },
    },
    {
      name: "Cobasi",
      email: "admin3@example.com",
      password: bcrypt.hashSync("asdf", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Coabasi seller",
        logo: "/images/seller/cobasi.png",
        description: "best seller",
        rating: 2.5,
        numReviews: 120,
      },
    },
    {
      name: "Extra",
      email: "admin4@example.com",
      password: bcrypt.hashSync("asdf", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Extra seller",
        logo: "/images/seller/extra.png",
        description: "best seller",
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: "Wallmart",
      email: "admin5@example.com",
      password: bcrypt.hashSync("asdf", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Wallmart seller",
        logo: "/images/seller/wallmart.png",
        description: "best seller",
        rating: 5,
        numReviews: 120,
      },
    },
    {
      name: "Pet Love",
      email: "admin6@example.com",
      password: bcrypt.hashSync("asdf", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Pet Love seller",
        logo: "/images/petlove.png",
        description: "best seller",
        rating: 1,
        numReviews: 120,
      },
    },
    {
      name: "John",
      email: "user1@example.com",
      password: bcrypt.hashSync("asdf", 8),
      isAdmin: false,
    },
  ],
  categories: [
    {
      name: "gato",
      description: "Categoria feita para felinos",
      image: "",
      categoryId: "gato",
      parentCategoryId: "root",
      online: true,
    },
    {
      name: "brinquedo",
      description: "Categoria de brinquedos",
      image: "",
      categoryId: "brinquedo",
      parentCategoryId: "gato",
      online: true,
    },
    {
      name: "comida",
      description: "Categoria de comidas",
      image: "",
      categoryId: "comida",
      parentCategoryId: "gato",
      online: true,
    },
    {
      name: "roupa",
      description: "Categoria de roupas",
      image: "",
      categoryId: "roupa",
      parentCategoryId: "gato",
      online: true,
    },
    {
      name: "marca",
      description: "Categoria de marcas",
      image: "",
      categoryId: "marca",
      parentCategoryId: "gato",
      online: true,
    },
    {
      name: "cão",
      description: "Categoria feita para cães",
      image: "",
      categoryId: "cao",
      parentCategoryId: "root",
      online: true,
    },
    {
      name: "brinquedo",
      description: "Categoria de brinquedos",
      image: "",
      categoryId: "brinquedo",
      parentCategoryId: "cao",
      online: true,
    },
    {
      name: "comida",
      description: "Categoria de comidas",
      image: "",
      categoryId: "comida",
      parentCategoryId: "cao",
      online: true,
    },
    {
      name: "roupa",
      description: "Categoria de roupas",
      image: "",
      categoryId: "roupa",
      parentCategoryId: "cao",
      online: true,
    },
    {
      name: "marca",
      description: "Categoria de marcas",
      image: "",
      categoryId: "marca",
      parentCategoryId: "cao",
      online: true,
    },
    {
      name: "outro",
      description: "Categoria feita para outros",
      image: "",
      categoryId: "outro",
      parentCategoryId: "root",
      online: true,
    },
    {
      name: "brinquedo",
      description: "Categoria de brinquedos",
      image: "",
      categoryId: "brinquedo",
      parentCategoryId: "outro",
      online: true,
    },
    {
      name: "comida",
      description: "Categoria de comidas",
      image: "",
      categoryId: "comida",
      parentCategoryId: "outro",
      online: true,
    },
    {
      name: "roupa",
      description: "Categoria de roupas",
      image: "",
      categoryId: "roupa",
      parentCategoryId: "outro",
      online: true,
    },
    {
      name: "marca",
      description: "Categoria de marcas",
      image: "",
      categoryId: "marca",
      parentCategoryId: "outro",
      online: true,
    },
    {
      name: "ave",
      description: "Categoria de aves",
      image: "",
      categoryId: "ave",
      parentCategoryId: "root",
      online: true,
    },
    {
      name: "brinquedo",
      description: "Categoria de brinquedos",
      image: "",
      categoryId: "brinquedo",
      parentCategoryId: "ave",
      online: true,
    },
    {
      name: "comida",
      description: "Categoria de comidas",
      image: "",
      categoryId: "comida",
      parentCategoryId: "ave",
      online: true,
    },
    {
      name: "roupa",
      description: "Categoria de roupas",
      image: "",
      categoryId: "roupa",
      parentCategoryId: "ave",
      online: true,
    },
    {
      name: "marca",
      description: "Categoria de marcas",
      image: "",
      categoryId: "marca",
      parentCategoryId: "ave",
      online: true,
    },
    {
      name: "brinquedo",
      description: "Categoria de brinquedos",
      image: "",
      categoryId: "brinquedo",
      parentCategoryId: "root",
      online: true,
    },
    {
      name: "comida",
      description: "Categoria de comidas",
      image: "",
      categoryId: "comida",
      parentCategoryId: "root",
      online: true,
    },
    {
      name: "roupa",
      description: "Categoria de roupas",
      image: "",
      categoryId: "roupa",
      parentCategoryId: "root",
      online: true,
    },
    {
      name: "marca",
      description: "Categoria de marcas",
      image: "",
      categoryId: "marca",
      parentCategoryId: "root",
      online: true,
    },
    {
      name: "oferta",
      description: "Categoria de ofertas",
      image: "",
      categoryId: "oferta",
      parentCategoryId: "root",
      online: true,
    },
  ],
  products: [
    {
      name: "Pote de ração vermelho",
      categoryName: "cao",
      categoryData: "60a1e94e201d017cfd8fee1f",
      seller: "60a1e089840b508641efb75c",
      image: [
        "/images/product/pote_de_racao_vermelho.png",
        "/images/product/pote_de_racao_vermelho.png",
        "/images/product/pote_de_racao_vermelho.png",
        "/images/product/pote_de_racao_vermelho.png",
        "/images/product/pote_de_racao_vermelho.png",
      ],
      oldPrice: 32,
      newPrice: 20,
      countInStock: 10,
      brand: "Dog Show",
      rating: 4,
      numReviews: 15,
      description:
        "Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães",
      sellQty: 543,
    },
    {
      name: "Ração de Gato",
      categoryName: "gato",
      categoryData: "60a1e94e201d017cfd8fee1a",
      seller: "60a1e089840b508641efb75c",
      image: [
        "/images/product/racao_de_gato.jpg",
        "/images/product/racao_de_gato.jpg",
        "/images/product/racao_de_gato.jpg",
        "/images/product/racao_de_gato.jpg",
        "/images/product/racao_de_gato.jpg",
      ],
      oldPrice: 67,
      newPrice: 56,
      countInStock: 10,
      brand: "Whiskas",
      rating: 3,
      numReviews: 25,
      description:
        "Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos",
      sellQty: 233,
    },
    {
      name: "Brinquedo de cachorro",
      categoryName: "cao",
      categoryData: "60a1e94e201d017cfd8fee1f",
      seller: "60a1e089840b508641efb75c",
      image: [
        "/images/product/brinquedo_de_cachorro.jpg",
        "/images/product/brinquedo_de_cachorro.jpg",
        "/images/product/brinquedo_de_cachorro.jpg",
        "/images/product/brinquedo_de_cachorro.jpg",
        "/images/product/brinquedo_de_cachorro.jpg",
      ],
      oldPrice: 150,
      newPrice: 120,
      countInStock: 12,
      brand: "Dog Toy",
      rating: 3,
      numReviews: 115,
      description:
        "Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães",
      sellQty: 10,
    },
    {
      name: "Pote de ração azul",
      categoryName: "gato",
      categoryData: "60a1e94e201d017cfd8fee1a",
      seller: "60a1e089840b508641efb75c",
      image: [
        "/images/product/pode_de_raca_azul.jpg",
        "/images/product/pode_de_raca_azul.jpg",
        "/images/product/pode_de_raca_azul.jpg",
        "/images/product/pode_de_raca_azul.jpg",
        "/images/product/pode_de_raca_azul.jpg",
      ],
      oldPrice: 65,
      newPrice: 20,
      countInStock: 13,
      brand: "Cat Show",
      rating: 5,
      numReviews: 15,
      description:
        "Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos",
      sellQty: 34,
    },
    {
      name: "Ração úmida para gato",
      categoryName: "gato",
      categoryData: "60a1e94e201d017cfd8fee1a",
      seller: "60a1e089840b508641efb75c",
      image: [
        "/images/product/racao_umida_para_gato.jpg",
        "/images/product/racao_umida_para_gato.jpg",
        "/images/product/racao_umida_para_gato.jpg",
        "/images/product/racao_umida_para_gato.jpg",
        "/images/product/racao_umida_para_gato.jpg",
      ],
      oldPrice: 7.49,
      newPrice: 2.49,
      countInStock: 1120,
      brand: "Cat Show",
      rating: 4,
      numReviews: 15,
      description:
        "Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos",
      sellQty: 54,
    },
    {
      name: "Ração para cachorro",
      categoryName: "cao",
      categoryData: "60a1e94e201d017cfd8fee1f",
      seller: "60a1e089840b508641efb75c",
      image: [
        "/images/product/racao_para_cachorro.jpg",
        "/images/product/racao_para_cachorro.jpg",
        "/images/product/racao_para_cachorro.jpg",
        "/images/product/racao_para_cachorro.jpg",
        "/images/product/racao_para_cachorro.jpg",
      ],
      oldPrice: 85,
      newPrice: 59,
      countInStock: 210,
      brand: "Pedigree",
      rating: 4,
      numReviews: 125,
      description:
        "Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães",
      sellQty: 47,
    },
    {
      name: "Ração úmida para cachorro",
      categoryName: "cao",
      categoryData: "60a1e94e201d017cfd8fee1f",
      seller: "60a1e089840b508641efb75c",
      image: [
        "/images/product/racao_umida_para_cachorro.jpg",
        "/images/product/racao_umida_para_cachorro.jpg",
        "/images/product/racao_umida_para_cachorro.jpg",
        "/images/product/racao_umida_para_cachorro.jpg",
        "/images/product/racao_umida_para_cachorro.jpg",
      ],
      oldPrice: 76,
      newPrice: 20,
      countInStock: 10,
      brand: "Pedigree",
      rating: 2,
      numReviews: 315,
      description:
        "Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães",
      sellQty: 53,
    },
    {
      name: "Bolinha de borracha",
      categoryName: "cao",
      categoryData: "60a1e94e201d017cfd8fee1f",
      seller: "60a1e089840b508641efb75c",
      image: [
        "/images/product/bolinha_de_borracha.jpg",
        "/images/product/bolinha_de_borracha.jpg",
        "/images/product/bolinha_de_borracha.jpg",
        "/images/product/bolinha_de_borracha.jpg",
        "/images/product/bolinha_de_borracha.jpg",
      ],
      oldPrice: 75.5,
      newPrice: 26.5,
      countInStock: 110,
      brand: "Dog Show",
      rating: 4,
      numReviews: 15,
      description:
        "Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães Excelente produto para cães",
      sellQty: 3,
    },
    {
      name: "Vara com pena",
      categoryName: "gato",
      categoryData: "60a1e94e201d017cfd8fee1a",
      seller: "60a1e089840b508641efb75c",
      image: [
        "/images/product/vara_com_pena.png",
        "/images/product/vara_com_pena.png",
        "/images/product/vara_com_pena.png",
        "/images/product/vara_com_pena.png",
        "/images/product/vara_com_pena.png",
      ],
      oldPrice: 44,
      newPrice: 14,
      countInStock: 117,
      brand: "Cat Show",
      rating: 4,
      numReviews: 15,
      description:
        "Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos",
      sellQty: 0,
    },
    {
      name: "Roupa de gato",
      categoryName: "gato",
      categoryData: "60a1e94e201d017cfd8fee1a",
      seller: "60a1e089840b508641efb75c",
      image: [
        "/images/product/roupa_de_gato.jpg",
        "/images/product/roupa_de_gato.jpg",
        "/images/product/roupa_de_gato.jpg",
        "/images/product/roupa_de_gato.jpg",
        "/images/product/roupa_de_gato.jpg",
      ],
      oldPrice: 43,
      newPrice: 27,
      countInStock: 12,
      brand: "Cat Fashion",
      rating: 5,
      numReviews: 15,
      description:
        "Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos Excelente produto para gatos",
      sellQty: 2,
    },
    {
      name: "Roupa de cachorro",
      categoryName: "cao",
      categoryData: "60a1e94e201d017cfd8fee1f",
      seller: "60a1e089840b508641efb75c",
      image: [
        "/images/product/roupa_de_cachorro.jpg",
        "/images/product/roupa_de_cachorro.jpg",
        "/images/product/roupa_de_cachorro.jpg",
        "/images/product/roupa_de_cachorro.jpg",
        "/images/product/roupa_de_cachorro.jpg",
      ],
      oldPrice: 27,
      newPrice: 17,
      countInStock: 12,
      brand: "Cat Fashion",
      rating: 3.5,
      numReviews: 178,
      description:
        "Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros Excelente produto para cachorros",
      sellQty: 1,
    },
  ],
};

export default data;
