import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Kiyoshi",
      email: "admin1@example.com",
      password: bcrypt.hashSync("asdf", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Kiyoshi seller",
        logo: "/images/matsumotokiyoshi.png",
        description: "best seller",
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: "Carrefour",
      email: "admin2@example.com",
      password: bcrypt.hashSync("asdf", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Carrefour seller",
        logo: "/images/seller/carrefour.png",
        description: "best seller",
        rating: 3.5,
        numReviews: 120,
      },
    },
    {
      name: "Cobasi",
      email: "admin3@example.com",
      password: bcrypt.hashSync("asdf", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Coabasi seller",
        logo: "/images/seller/cobasi.png",
        description: "best seller",
        rating: 2.5,
        numReviews: 120,
      },
    },
    {
      name: "Extra",
      email: "admin4@example.com",
      password: bcrypt.hashSync("asdf", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Extra seller",
        logo: "/images/seller/extra.png",
        description: "best seller",
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: "Wallmart",
      email: "admin5@example.com",
      password: bcrypt.hashSync("asdf", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Wallmart seller",
        logo: "/images/seller/wallmart.png",
        description: "best seller",
        rating: 5,
        numReviews: 120,
      },
    },
    {
      name: "Pet Love",
      email: "admin6@example.com",
      password: bcrypt.hashSync("asdf", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Pet Love seller",
        logo: "/images/petlove.png",
        description: "best seller",
        rating: 1,
        numReviews: 120,
      },
    },
    {
      name: "John",
      email: "user1@example.com",
      password: bcrypt.hashSync("asdf", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Pote de ração vermelho",
      category: "cachorro",
      image: "/images/product/pote_de_racao_vermelho.jpg",
      price: 20,
      countInStock: 10,
      brand: "Dog Show",
      rating: 4,
      numReviews: 15,
      description: "Excelente produto para cães",
    },
    {
      name: "Ração de Gato",
      category: "gato",
      image: "/images/product/racao_de_gato.jpg",
      price: 56,
      countInStock: 10,
      brand: "Whiskas",
      rating: 3,
      numReviews: 25,
      description: "Excelente produto para gatos",
    },
    {
      name: "Brinquedo de cachorro",
      category: "cachorro",
      image: "/images/product/brinquedo_de_cachorro.jpg",
      price: 120,
      countInStock: 12,
      brand: "Dog Toy",
      rating: 3,
      numReviews: 115,
      description: "Excelente produto para cães",
    },
    {
      name: "Pote de ração azul",
      category: "gato",
      image: "/images/product/pode_de_raca_azul.jpg",
      price: 20,
      countInStock: 13,
      brand: "Cat Show",
      rating: 5,
      numReviews: 15,
      description: "Excelente produto para gatos",
    },
    {
      name: "Ração úmida para gato",
      category: "gato",
      image: "/images/product/racao_umida_para_gato.jpg",
      price: 2.49,
      countInStock: 1120,
      brand: "Cat Show",
      rating: 4,
      numReviews: 15,
      description: "Excelente produto para gatos",
    },
    {
      name: "Ração para cachorro",
      category: "cachorro",
      image: "/images/product/racao_para_cachorro.jpg",
      price: 59,
      countInStock: 210,
      brand: "Pedigree",
      rating: 4,
      numReviews: 125,
      description: "Excelente produto para cães",
    },
    {
      name: "Ração úmida para cachorro",
      category: "cachorro",
      image: "/images/product/racao_umida_para_cachorro.jpg",
      price: 20,
      countInStock: 10,
      brand: "Pedigree",
      rating: 2,
      numReviews: 315,
      description: "Excelente produto para cães",
    },
    {
      name: "Bolinha de borracha",
      category: "cachorro",
      image: "/images/product/bolinha_de_borracha.jpg",
      price: 26.5,
      countInStock: 110,
      brand: "Dog Show",
      rating: 4,
      numReviews: 15,
      description: "Excelente produto para cães",
    },
    {
      name: "Vara com pena",
      category: "gato",
      image: "/images/product/vara_com_pena.jpg",
      price: 14,
      countInStock: 117,
      brand: "Cat Show",
      rating: 4,
      numReviews: 15,
      description: "Excelente produto para gatos",
    },
    {
      name: "Roupa de gato",
      category: "gato",
      image: "/images/product/roupa_de_gato.jpg",
      price: 27,
      countInStock: 12,
      brand: "Cat Fashion",
      rating: 5,
      numReviews: 15,
      description: "Excelente produto para gatos",
    },
    {
      name: "Roupa de cachorro",
      category: "cachorro",
      image: "/images/product/roupa_de_cachorro.jpg",
      price: 17,
      countInStock: 12,
      brand: "Cat Fashion",
      rating: 3.5,
      numReviews: 178,
      description: "Excelente produto para cachorros",
    },
  ],
};

export default data;
